spring:
  jpa:
    database: mysql
    hibernate:
      ddl-auto: create
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/carwith
    username: root
    password: tkwkajfl147!

#  profiles:
#    active: local
#    include: oauth
#

jwt:
  issuer: jwa4610@gmail.com
  secret_key: carwith-project-by-sangwonjwa

#app:
#  auth:
#    tokenSecret: TOKEN_SECRET
#    tokenExpiry: 1800000
#    refreshTokenExpiry: 6048000000
#  oauth2:
#    authorizedRedirectUris:
#      - http://localhost:3000/oauth/redirect

#logging:
#  level:
#    org.hibernate: debug